### ISSUE TITLE
List of [enchant] Token

### ISSUE THREAD

**Issue by JustKing009** [haydenred/LevelTools#4]
efficiency = DIG_SPEED
What's Token for ?
- smite
- silk_touch
- piercing
- thorns
- flame
- fortune
- luck_of_the_sea
- chopping
- unbreaking
- lure
- multishot
- bane_of_arthropods
- looting
- mending
- knockback
- sharpness
- punch
- quick_charge
- sweeping
- power
- infinity
- fire_aspect

**Comment by haydenred** [comment]
[This](https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XEnchantment.java) should have everything you need. Let me know if you have any further questions in discord
